### ISSUE TITLE
Errors in .ann files

### ISSUE THREAD

**Issue by huwstrafford** [samueldobbie/markup#12]
EXAMPLE .ANN FILE

T1	AnnotationName1 218 233	String1
A1	Feature1 T1 A
**A2**	Feature2 T1 B
A3	Feature3 T1 C
T2	AnnotationName2 262 272	String2
**A2**	Feature4 T2 Other

If you have the same identifier for features (**A2**) in one .ann file then GATE will only add one of the features.

**Comment by samueldobbie** [comment]
Fixed in refactor (branch tidy/react-ts-refactor) which will be merged into mainline soon.
