### ISSUE TITLE
How to download all annotations of different documents at once?

### ISSUE THREAD

**Issue by liebkne** [samueldobbie/markup#21]
I can't find a button to do so...

**Comment by samueldobbie** [comment]
There's no option to do so in the current version (which is no longer being worked on), but this is an option in the rework of the tool that will be released in the coming weeks. Will keep this issue open and update when available.

**Comment by samueldobbie** [comment]
You can try the upcoming version here: [https://markup-dev-e0b29.web.app/](https://markup-dev-e0b29.web.app/). If you use it, I'd suggest treating your account and uploaded docs as ephemeral until a production version is released, as db's may be dropped without notice, etc.
