### ISSUE TITLE
Record multiple values for the same attribute

### ISSUE THREAD

**Issue by arronlacey** [samueldobbie/markup#28]
If I have an entity A, and it has an attribute B, could we allow to record multiple values for B. i.e. if B denotes risk factors for heart disease there might be a drop down list that includes smoking, high BMI and we would want to include both of those. Currently we can only pick one and the workaround is to annotate two separate entities, one for each attribute value.

**Comment by samueldobbie** [comment]
Thanks for the suggestion; feature has been added to V2
