### ISSUE TITLE
Conf File CRLF vs LF

### ISSUE THREAD

**Issue by huwstrafford** [samueldobbie/markup#33]
Issue with end of line character for .conf files. Cannot attach files as .conf so are as .conf.txt. Only LF will work. 
[annotationCRLF.txt](https://github.com/samueldobbie/markup/files/8799592/annotationCRLF.txt)
[annotationLF.conf.txt](https://github.com/samueldobbie/markup/files/8799593/annotationLF.conf.txt)
![image](https://user-images.githubusercontent.com/46718817/171027553-4ef6e96f-f199-4a41-8975-32e6439ab0dc.png)
Image of console error also provided - parseCategories() in Helper.ts looks like the issue

**Comment by samueldobbie** [comment]
Resolved in V2
