### ISSUE TITLE
You need to provide valid config file. ERROR

### ISSUE THREAD

**Issue by williamtraynor** [samueldobbie/markup#34]
I am attempting to create a new page, similar to annotate, called **analyse**. Initially, I simply duplicated the annotate file and renamed all relevant annotate variables to **analyse**. Now when I upload a folder and try to start a session I receive the error shown below which asks for me to provide a valid config file. I am unsure why this issue arises as following the functions called when clicking the button everything for **analyse** is the same as annotate. So I am uncertain if the issue lies in another function which actually uploads the files selected on the setup page. 

Any help with this issue would be greatly appreciated and please let me know if you need me to elaborate any more. 

Thank you, William

<img width="463" alt="Screenshot 2022-06-15 at 13 52 44" src="https://user-images.githubusercontent.com/59997793/173831519-c684bc58-3122-4f6f-a4b9-af361c183f8c.png">

**Comment by arronlacey** [comment]
Hi @williamtraynor is this the `annotation.config` file that is being replaced?

**Comment by williamtraynor** [comment]
I am unsure, where is the annotation.config file located? I thought it had to do with the localStorage variable and that the file that I am uploading for some reason cannot be retrieved properly. However there are no issues when I use the annotate webpage, only when I try to use my newly created analyse webpage.

I hope this helps

**Comment by huwstrafford** [comment]
I think your local storage is being cleared.
Check the static/js/base.js file where this is done and add analyse as one to ignore

**Comment by samueldobbie** [comment]
Fixed as V2 no longer uses local storage for handling the config file
