### ISSUE TITLE
demo documents are very heavily pre-annotated

### ISSUE THREAD

**Issue by arronlacey** [samueldobbie/markup#47]
At least for letter 0 the document is very heavily annotated - should the demo have just a few annotations only to give the user an idea of what they can try themselves?

**Comment by samueldobbie** [comment]
Good catch. The issue stems from the fact that the public demo session is globally accessible / shared across all users; will either update it so demo annotations are local to the user, or setup a schedule to wipe them every X hours.

**Comment by samueldobbie** [comment]
I've setup a cron job that will periodically drop the demo annotations.
