### ISSUE TITLE
Hi from the author of Mantine DataTable

### ISSUE THREAD

**Issue by icflorescu** [samueldobbie/markup#93]
Hey @samueldobbie,

This is @icflorescu, the author of [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) open-source component.

I'm glad to discover you are using Mantine DataTable in [MARKUP](https://www.getmarkup.com/).
Would you care to share a bit of feedback with me regarding your experience with it?
I'm trying to understand the users' stories and experience with my component in order to see how/if I could further improve the project.

Also, I'm planning to compile a list of startups / projects that are using Mantine DataTable and add it to the project's documentation website. Would you be ok with me adding a logo/link to [MARKUP](https://www.getmarkup.com/)?

Thanks a lot for using [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) and apologies for approaching you like this!

**Comment by samueldobbie** [comment]
Thanks for creating it - I've yet to stretch it far enough to provide useful feedback, but it has been great thus far!

Happy for you to add a link to Markup on your docs.

**Comment by icflorescu** [comment]
Thanks a lot!
